from langchain.agents import create_agent
from dotenv import load_dotenv
import os 

load_dotenv()

# check the env variables
if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY is not set in the environment variables.")

# Let's create the first agent 
writer_agent = create_agent(
    # model="google_genai:gemini-3.1-pro-preview", #brain
    model="openai:gpt-5.4", #brain
    tools=[], # register the tool with the agent
    system_prompt="""You are creative writer working in a top media company. 
    Your task is to generate engaging content and provide insightful 
    updates on various topics."""
)

# Let's create the second agent
editor_agent = create_agent(
    # model="google_genai:gemini-3.1-pro-preview", #brain
    model="openai:gpt-5.4", #brain
    tools=[], # register the tool with the agent
    system_prompt="""You are an editor working in a top media company.
    Your task is to review the content generated by the writer and provide
    constructive feedback to enhance the quality and engagement of the content 
    and along with it you rewrite if necessary."""
)

print("Created 2 Agents - Writer and Editor successfully!")





# let's define sequential execution pipeline of the agents 
def sequential_execution_pipeline(topic):
    """
      Sequential Execution Pipeline:
      1. The Writer Agent generates content based on the given topic.
      2. The Editor Agent reviews the generated content and provides feedback to enhance it.
      3. The Editor Agent may also rewrite the content if necessary to improve its quality and engagement.
    """
    # Step 1: Writer agent generates content
    writer_result = writer_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": f"Generate engaging content on the topic: {topic}"
                }
            ]
        }
    )
    print("\nWriter Agent Response:")
    print(writer_result["messages"][-1].content)

    # Step 2: Editor agent reviews and provides feedback
    editor_result = editor_agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": f"""Review the following content:                    
                      {writer_result['messages'][-1].content}

                      Enhance it if needed to make it more engaging, clear, and insightful while keeping the original meaning intact.

                      Also provide a short feedback section covering:
                      - What was improved
                      - Why the improvements help
                      - Any remaining suggestions

                      Focus on:
                      - Clarity
                      - Readability
                      - Flow
                      - Engagement
                      - Grammar and wording
                    """
                }
            ]
        }
    )
    print("\n================= Editor Agent Response Ready and Processed: ======================")
    refined_content = editor_result["messages"][-1].content
    return {
        "topic": topic,
        "writer_content": writer_result["messages"][-1].content, #draft content
        "refined_content": refined_content # final content after editor's review and feedback
    }

# Let's test the sequential execution pipeline with a sample topic  
if __name__ == "__main__":
    sample_topic = input("Enter a topic for the Writer Agent to generate content on: ")
    result = sequential_execution_pipeline(sample_topic)
    print("\nFinal Refined Content:")
    print(result["refined_content"])
